#!/bin/bash
set -e

echo
echo Mac Scripts - Help
echo 
echo Commands list:
echo "  ./help         - Lists all available commands."
echo "  ./brew-install - Installs all most commonly used formulae and casks via Homebrew."
echo "  ./update       - Updates Homebrew and upgrades all packages that have been installed via Homebrew."
echo